framework:
    rate_limiter:
        login_attempt:
            policy: fixed_window
            limit: 5
            interval: '15 minutes'

        otp_attempt:
            policy: fixed_window
            limit: 5
            interval: '15 minutes'